version: "3.3"
services:
  db:
    container_name: database
    image: postgres:13
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: "backend.dockerfile"
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/backend
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=2
      - WAIT_HOST_CONNECT_TIMEOUT=5
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_SERVER=db
      - JWT_SECRET=somesecret
    user: ${UID}:${GID}
  frontend:
    build:
      context: frontend/
      dockerfile:  "Dockerfile"
    ports:
      - 1234:1234
    volumes:
      - ./frontend/:/usr/src/frontend
    environment:
      - API_URL=http://backend:5000
      - WAIT_HOSTS=backend:5000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=2
      - WAIT_HOST_CONNECT_TIMEOUT=5
