-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Mutation exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateTradingPartnerOptionalArguments =
    { adress : OptionalArgument String
    , name : OptionalArgument String
    , nipNumber : OptionalArgument String
    }


createTradingPartner :
    (CreateTradingPartnerOptionalArguments -> CreateTradingPartnerOptionalArguments)
    -> SelectionSet decodesTo Backend.Object.CreateTradingPartner
    -> SelectionSet (Maybe decodesTo) RootMutation
createTradingPartner fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { adress = Absent, name = Absent, nipNumber = Absent }

        optionalArgs____ =
            [ Argument.optional "adress" filledInOptionals____.adress Encode.string, Argument.optional "name" filledInOptionals____.name Encode.string, Argument.optional "nipNumber" filledInOptionals____.nipNumber Encode.string ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "createTradingPartner" optionalArgs____ object____ (identity >> Decode.nullable)
