-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object exposing (..)


type CreateInvoice
    = CreateInvoice


type CreateTradingPartner
    = CreateTradingPartner


type Invoice
    = Invoice


type InvoicePosition
    = InvoicePosition


type TradingPartner
    = TradingPartner
