-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.ScalarCodecs exposing (..)

import Backend.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Backend.Scalar.Id


codecs : Backend.Scalar.Codecs Id
codecs =
    Backend.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
