-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.ScalarCodecs exposing (..)

import Backend.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Date =
    Backend.Scalar.Date


codecs : Backend.Scalar.Codecs Date
codecs =
    Backend.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        }
