"""Add environment

Revision ID: 2fad3e68131a
Revises: fdfd80095bfc
Create Date: 2021-04-19 16:51:17.671383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fad3e68131a'
down_revision = 'fdfd80095bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('invoice', sa.Column('enterprise', sa.Integer(), nullable=True))
    op.add_column('invoice', sa.Column('invoice_type', sa.String(length=8), nullable=False))
    op.create_foreign_key('fk_invoice_enterprise_id_enterprise', 'invoice', 'enterprise', ['enterprise'], ['id'])
    op.add_column('tradingpartner', sa.Column('enterprise', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tradingpartner_enterprise_id_enterprise', 'tradingpartner', 'enterprise', ['enterprise'], ['id'])
    op.add_column('vatrate', sa.Column('enterprise', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_vatrate_enterprise_id_enterprise', 'vatrate', 'enterprise', ['enterprise'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vatrate_enterprise_id_enterprise', 'vatrate', type_='foreignkey')
    op.drop_column('vatrate', 'enterprise')
    op.drop_constraint('fk_tradingpartner_enterprise_id_enterprise', 'tradingpartner', type_='foreignkey')
    op.drop_column('tradingpartner', 'enterprise')
    op.drop_constraint('fk_invoice_enterprise_id_enterprise', 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'invoice_type')
    op.drop_column('invoice', 'enterprise')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('enterprise')
    # ### end Alembic commands ###
