"""added enterprise fields

Revision ID: 48a8c454c0e5
Revises: dcec4f0c04b6
Create Date: 2021-06-27 14:58:43.366162

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "48a8c454c0e5"
down_revision = "dcec4f0c04b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enterprise", sa.Column("address", sa.String(length=256), nullable=True)
    )

    op.add_column(
        "enterprise", sa.Column("nip_number", sa.String(length=10), nullable=True)
    )
    op.execute("update enterprise set address='';")
    op.execute("update enterprise set nip_number='';")
    op.alter_column("enterprise", "address", nullable=False)
    op.alter_column("enterprise", "nip_number", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("enterprise", "nip_number")
    op.drop_column("enterprise", "address")
    # ### end Alembic commands ###
