"""empty message

Revision ID: 732561431e78
Revises: bb6536213ca6
Create Date: 2021-09-14 12:46:33.913294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732561431e78'
down_revision = '90f13c0c6117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoiceposition_invoice_id_invoice_id', 'invoiceposition', type_='foreignkey')
    op.create_foreign_key('fk_invoiceposition_invoice_id_invoice_id', 'invoiceposition', 'invoice', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoiceposition_invoice_id_invoice_id', 'invoiceposition', type_='foreignkey')
    op.create_foreign_key('fk_invoiceposition_invoice_id_invoice_id', 'invoiceposition', 'invoice', ['invoice_id'], ['id'])
    # ### end Alembic commands ###
