"""Add cascade delete
Revision ID: 90f13c0c6117
Revises: ca884ba4aac5
Create Date: 2021-08-23 15:36:56.122778
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f13c0c6117'
down_revision = 'ca884ba4aac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoice_enterprise_id_enterprise_id', 'invoice', type_='foreignkey')
    op.create_foreign_key('fk_invoice_enterprise_id_enterprise_id', 'invoice', 'enterprise', ['enterprise_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_tradingpartner_enterprise_id_enterprise_id', 'tradingpartner', type_='foreignkey')
    op.create_foreign_key('fk_tradingpartner_enterprise_id_enterprise_id', 'tradingpartner', 'enterprise', ['enterprise_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_userenterprise_enterprise_id_enterprise_id', 'userenterprise', type_='foreignkey')
    op.create_foreign_key('fk_userenterprise_enterprise_id_enterprise_id', 'userenterprise', 'enterprise', ['enterprise_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_vatrate_enterprise_id_enterprise_id', 'vatrate', type_='foreignkey')
    op.create_foreign_key('fk_vatrate_enterprise_id_enterprise_id', 'vatrate', 'enterprise', ['enterprise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vatrate_enterprise_id_enterprise_id', 'vatrate', type_='foreignkey')
    op.create_foreign_key('fk_vatrate_enterprise_id_enterprise_id', 'vatrate', 'enterprise', ['enterprise_id'], ['id'])
    op.drop_constraint('fk_userenterprise_enterprise_id_enterprise_id', 'userenterprise', type_='foreignkey')
    op.create_foreign_key('fk_userenterprise_enterprise_id_enterprise_id', 'userenterprise', 'enterprise', ['enterprise_id'], ['id'])
    op.drop_constraint('fk_tradingpartner_enterprise_id_enterprise_id', 'tradingpartner', type_='foreignkey')
    op.create_foreign_key('fk_tradingpartner_enterprise_id_enterprise_id', 'tradingpartner', 'enterprise', ['enterprise_id'], ['id'])
    op.drop_constraint('fk_invoice_enterprise_id_enterprise_id', 'invoice', type_='foreignkey')
    op.create_foreign_key('fk_invoice_enterprise_id_enterprise_id', 'invoice', 'enterprise', ['enterprise_id'], ['id'])
    # ### end Alembic commands ###