"""init

Revision ID: 914e4d1a3348
Revises: 
Create Date: 2021-07-08 07:30:57.959008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914e4d1a3348'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('nip_number', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('tradingpartner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nip_number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], name='fk_tradingpartner_enterprise_id_enterprise_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userenterprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], name='fk_userenterprise_enterprise_id_enterprise_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_userenterprise_user_id_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vatrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], name='fk_vatrate_enterprise_id_enterprise_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_business_id', sa.String(length=64), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_type', sa.String(length=8), nullable=False),
    sa.Column('trading_partner_id', sa.Integer(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], name='fk_invoice_enterprise_id_enterprise_id'),
    sa.ForeignKeyConstraint(['trading_partner_id'], ['tradingpartner.id'], name='fk_invoice_tradingpartner_id_trading_partner_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoiceposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('vat_rate_id', sa.Integer(), nullable=True),
    sa.Column('num_items', sa.Float(), nullable=False),
    sa.Column('price_net', sa.Float(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name='fk_invoiceposition_invoice_id_invoice_id'),
    sa.ForeignKeyConstraint(['vat_rate_id'], ['vatrate.id'], name='fk_invoiceposition_vatrate_id_vat_rate_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoiceposition')
    op.drop_table('invoice')
    op.drop_table('vatrate')
    op.drop_table('userenterprise')
    op.drop_table('tradingpartner')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('enterprise')
    # ### end Alembic commands ###
