"""Added username unique constraint

Revision ID: 97f670a8297b
Revises: ca884ba4aac5
Create Date: 2021-08-31 17:04:04.796996

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "97f670a8297b"
down_revision = "732561431e78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_username", table_name="user")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index("ix_user_username", "user", ["username"], unique=False)
    # ### end Alembic commands ###
