"""Add fav enterprise field

Revision ID: ca884ba4aac5
Revises: ad95e34ca8bc
Create Date: 2021-08-11 11:02:24.181650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca884ba4aac5'
down_revision = 'ad95e34ca8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fav_enterprise_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_enterprise_id_fav_enterprise_id', 'user', 'enterprise', ['fav_enterprise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_enterprise_id_fav_enterprise_id', 'user', type_='foreignkey')
    op.drop_column('user', 'fav_enterprise_id')
    # ### end Alembic commands ###
