"""added_userenterprise

Revision ID: dcec4f0c04b6
Revises: 2fad3e68131a
Create Date: 2021-06-04 15:59:16.218554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcec4f0c04b6'
down_revision = '2fad3e68131a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userenterprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.CHAR(36), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprise.id'], name='fk_userenterprise_enterprise_id_enterprise_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_userenterprise_users_id_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userenterprise')
    # ### end Alembic commands ###
