"""init

Revision ID: fdfd80095bfc
Revises: 
Create Date: 2021-04-19 15:25:23.625853

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fdfd80095bfc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tradingpartner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nip_number", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("adress", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vatrate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vat_rate", sa.Float(), nullable=False),
        sa.Column("comment", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invoice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.String(length=64), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("trading_partner", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_partner"],
            ["tradingpartner.id"],
            name="fk_invoice_tradingpartner_id_trading_partner",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invoiceposition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("vat_rate", sa.Integer(), nullable=True),
        sa.Column("num_items", sa.Float(), nullable=False),
        sa.Column("price_net", sa.Float(), nullable=False),
        sa.Column("invoice", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice"], ["invoice.id"], name="fk_invoiceposition_invoice_id_invoice"
        ),
        sa.ForeignKeyConstraint(
            ["vat_rate"], ["vatrate.id"], name="fk_invoiceposition_vatrate_id_vat_rate"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invoiceposition")
    op.drop_table("invoice")
    op.drop_table("vatrate")
    op.drop_table("tradingpartner")
    # ### end Alembic commands ###
