-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.CreateTradingPartner exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


ok : SelectionSet (Maybe Bool) Backend.Object.CreateTradingPartner
ok =
    Object.selectionForField "(Maybe Bool)" "ok" [] (Decode.bool |> Decode.nullable)


tradingPartner :
    SelectionSet decodesTo Backend.Object.TradingPartner
    -> SelectionSet (Maybe decodesTo) Backend.Object.CreateTradingPartner
tradingPartner object____ =
    Object.selectionForCompositeField "tradingPartner" [] object____ (identity >> Decode.nullable)
