-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.CreateInvoice exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


ok : SelectionSet (Maybe Bool) Backend.Object.CreateInvoice
ok =
    Object.selectionForField "(Maybe Bool)" "ok" [] (Decode.bool |> Decode.nullable)


invoice :
    SelectionSet decodesTo Backend.Object.Invoice
    -> SelectionSet (Maybe decodesTo) Backend.Object.CreateInvoice
invoice object____ =
    Object.selectionForCompositeField "invoice" [] object____ (identity >> Decode.nullable)


infoOutput : SelectionSet (Maybe String) Backend.Object.CreateInvoice
infoOutput =
    Object.selectionForField "(Maybe String)" "infoOutput" [] (Decode.string |> Decode.nullable)
