-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.Invoice exposing (..)

import Backend.Enum.InvoiceType
import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


uuid : SelectionSet Int Backend.Object.Invoice
uuid =
    Object.selectionForField "Int" "uuid" [] Decode.int


invoiceId : SelectionSet String Backend.Object.Invoice
invoiceId =
    Object.selectionForField "String" "invoiceId" [] Decode.string


invoiceDate : SelectionSet Backend.ScalarCodecs.Date Backend.Object.Invoice
invoiceDate =
    Object.selectionForField "ScalarCodecs.Date" "invoiceDate" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecDate |> .decoder)


invoiceType : SelectionSet Backend.Enum.InvoiceType.InvoiceType Backend.Object.Invoice
invoiceType =
    Object.selectionForField "Enum.InvoiceType.InvoiceType" "invoiceType" [] Backend.Enum.InvoiceType.decoder


partner :
    SelectionSet decodesTo Backend.Object.TradingPartner
    -> SelectionSet decodesTo Backend.Object.Invoice
partner object____ =
    Object.selectionForCompositeField "partner" [] object____ identity


invoicePositions :
    SelectionSet decodesTo Backend.Object.InvoicePosition
    -> SelectionSet (List decodesTo) Backend.Object.Invoice
invoicePositions object____ =
    Object.selectionForCompositeField "invoicePositions" [] object____ (identity >> Decode.list)
