-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.InvoicePosition exposing (..)

import Backend.Enum.VatRates
import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


uuid : SelectionSet Int Backend.Object.InvoicePosition
uuid =
    Object.selectionForField "Int" "uuid" [] Decode.int


name : SelectionSet (Maybe String) Backend.Object.InvoicePosition
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


vatRate : SelectionSet Backend.Enum.VatRates.VatRates Backend.Object.InvoicePosition
vatRate =
    Object.selectionForField "Enum.VatRates.VatRates" "vatRate" [] Backend.Enum.VatRates.decoder


numItems : SelectionSet Float Backend.Object.InvoicePosition
numItems =
    Object.selectionForField "Float" "numItems" [] Decode.float


priceNet : SelectionSet Float Backend.Object.InvoicePosition
priceNet =
    Object.selectionForField "Float" "priceNet" [] Decode.float
