-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.TradingPartner exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Backend.ScalarCodecs.Id Backend.Object.TradingPartner
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecId |> .decoder)


nipNumber : SelectionSet (Maybe String) Backend.Object.TradingPartner
nipNumber =
    Object.selectionForField "(Maybe String)" "nipNumber" [] (Decode.string |> Decode.nullable)


name : SelectionSet (Maybe String) Backend.Object.TradingPartner
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


adress : SelectionSet (Maybe String) Backend.Object.TradingPartner
adress =
    Object.selectionForField "(Maybe String)" "adress" [] (Decode.string |> Decode.nullable)
