name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name : Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup elm
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - name: Install pipenv
        working-directory: ./backend
        run: python -m pip install --upgrade pip pipenv
      - name: Intall Python dependencies
        working-directory: ./backend/
        run: pipenv install
      - name : Build frontend
        run: ./scripts/build_frontend.sh
