name: Run tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup dependencies
        run: |
          pip3 install pipenv
          pipenv install --dev
      - name: Build coverage file
        run: DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres pipenv run  pytest --cache-clear --cov=app --cov-report xml
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: pytest
  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1

      - name: Setup elm
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1

      - name: Install dependencies
        run: |
          cd frontend
          npm install -g elm-test
          npm install -g elm-spa
          elm-spa gen
          elm-test

#       - name: Build frontend
#         run: ./scripts/build_frontend.sh
#       - name: Auto Minify
#         uses: nizarmah/auto-minify@master
#         with:
#           directory: "static"
#       - name: Auto committing minified files
#         uses: stefanzweifel/git-auto-commit-action@v3.0.0
#         with:
#           commit_message: "Github Action: Auto Minified JS and CSS files"
#           branch: ${{ github.ref }}\
