name: Run tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: |
          cd frontend
          npm install -g elm-test
          elm-test

#       - name: Setup elm
#         uses: jorelali/setup-elm@v3
#         with:
#           elm-version: 0.19.1
#       - name: Build frontend
#         run: ./scripts/build_frontend.sh
#       - name: Auto Minify
#         uses: nizarmah/auto-minify@master
#         with:
#           directory: "static"
#       - name: Auto committing minified files
#         uses: stefanzweifel/git-auto-commit-action@v3.0.0
#         with:
#           commit_message: "Github Action: Auto Minified JS and CSS files"
#           branch: ${{ github.ref }}\
